<a href="https://colab.research.google.com/github/Edwinshajan2006/data-science-/blob/main/Mall_Customer_Segmentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mall Customer Segmentation - Machine Learning Pipeline

This repository contains a Jupyter Notebook detailing a machine learning pipeline for mall customer segmentation. The steps include data loading, null value checking, categorical data encoding, feature and target separation, data splitting into training and testing sets, model selection (Linear Regression), model training, prediction, and accuracy evaluation.

# Mall Customer Segmentation - Machine Learning Pipeline

In [10]:
import pandas as pd
df=pd.read_csv('/content/Mall_Customers.csv')
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [11]:
#Q1
print(df.isnull().sum())

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [12]:
#Q2
df_encoded = pd.get_dummies(df, columns=['Gender'], drop_first=True)
display(df_encoded.head())

   CustomerID  Age  Annual Income (k$)  Spending Score (1-100)  Gender_Male
0           1   19                  15                      39         True
1           2   21                  15                      81         True
2           3   20                  16                       6        False
3           4   23                  16                      77        False
4           5   31                  17                      40        False

In [13]:
#Q3
X = df_encoded.drop(['CustomerID', 'Spending Score (1-100)'], axis=1)
y = df_encoded['Spending Score (1-100)']

print("Features (X) shape:", X.shape)
print("Target (y) shape:", y.shape)
display(X.head())

Features (X) shape: (200, 3)
Target (y) shape: (200,)

   Age  Annual Income (k$)  Gender_Male
0   19                  15         True
1   21                  15         True
2   20                  16        False
3   23                  16        False
4   31                  17        False

In [14]:
#Q4
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (160, 3)
X_test shape: (40, 3)
y_train shape: (160,)
y_test shape: (40,)

In [15]:
#Q5
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

print("Model training complete.")

Model training complete.

In [16]:
#Q6 AND Q7
y_pred = model.predict(X_test)

print("Predictions made on the test set.")
display(pd.DataFrame({'Actual': y_test, 'Predicted': y_pred}).head())

Predictions made on the test set.

     Actual  Predicted
95       52  59.828129
15       79  58.849457
30        4  37.046989
158       1  54.918427
128      11  39.843295

In [17]:
#Q8
from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error: {mae:.2f}")
print(f"R-squared: {r2:.2f}")

Mean Absolute Error: 18.15
R-squared: 0.03