<a href="https://colab.research.google.com/github/Edwinshajan2006/data-science-/blob/main/PANDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#!pip   install pandas

In [5]:
import pandas as pd
import numpy as np

In [6]:

df = pd.read_excel("/content/students_eda_dataset.xlsx")

In [7]:
# Q1 A

df.head()

,student_id,name,gender,department,attendance,marks,age,semester,city,scholarship
0,1,Rahul,Male,Mechanical,95,NaN,NaN,5,Thrissur,No
1,2,Anu,Male,Civil,62,NaN,18.0,1,Calicut,No
2,3,Vishnu,Male,Computer Science,90,36.0,NaN,1,Calicut,Yes
3,4,Sachin,Male,Computer Science,85,90.0,23.0,5,Kochi,No
4,5,Vimal,Female,Civil,99,NaN,NaN,1,Trivandrum,Yes

In [8]:
#Q1 B

df.tail()

,student_id,name,gender,department,attendance,marks,age,semester,city,scholarship
45,46,Vimal,Female,Mechanical,85,77.0,NaN,2,Kochi,Yes
46,47,Neha,Male,Civil,60,NaN,25.0,1,Calicut,Yes
47,48,Arjun,Male,Civil,73,36.0,25.0,6,Thrissur,No
48,49,Vimal,Female,Mechanical,80,74.0,25.0,4,Trivandrum,Yes
49,50,Pooja,Male,Electrical,62,NaN,NaN,4,Trivandrum,Yes

In [10]:
#Q1 C

df.shape

(50, 10)

In [11]:
#2 a
df.dtypes

student_id       int64
name            object
gender          object
department      object
attendance       int64
marks          float64
age            float64
semester         int64
city            object
scholarship     object
dtype: object

In [14]:
#2 b
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   50 non-null     int64
 1   name         50 non-null     object
 2   gender       50 non-null     object
 3   department   50 non-null     object
 4   attendance   50 non-null     int64
 5   marks        24 non-null     float64
 6   age          28 non-null     float64
 7   semester     50 non-null     int64
 8   city         50 non-null     object
 9   scholarship  50 non-null     object
dtypes: float64(2), int64(3), object(5)
memory usage: 4.0+ KB

In [16]:
#2 c

(df.shape[0])

50

In [18]:
#2 d
df.shape[1]

10

In [23]:
#2 e
df.memory_usage(deep=True)

Index           132
student_id      400
name           2693
gender         2702
department     2936
attendance      400
marks           400
age             400
semester        400
city           2825
scholarship    2575
dtype: int64

In [24]:
#Q3
df.columns

Index(['student_id', 'name', 'gender', 'department', 'attendance', 'marks',
       'age', 'semester', 'city', 'scholarship'],
      dtype='object')

In [28]:
#Q4 A
df.isnull().sum()

student_id      0
name            0
gender          0
department      0
attendance      0
marks          26
age            22
semester        0
city            0
scholarship     0
dtype: int64

In [29]:
#Q4 B
num_cols = df.select_dtypes(include=['int64','float64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

In [30]:
#Q4 C
cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

print(df.isnull().sum())

student_id     0
name           0
gender         0
department     0
attendance     0
marks          0
age            0
semester       0
city           0
scholarship    0
dtype: int64

/tmp/ipykernel_7199/2505152813.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [31]:
#Q5
df.mean(numeric_only=True)

student_id    25.500000
attendance    80.380000
marks         57.041667
age           21.714286
semester       3.260000
dtype: float64

In [32]:
#Q 5 b a

df.min(numeric_only=True)

student_id     1.0
attendance    60.0
marks         34.0
age           18.0
semester       1.0
dtype: float64

In [33]:
#Q 5 b b
df.max(numeric_only=True)

student_id     50.0
attendance    100.0
marks          92.0
age            25.0
semester        6.0
dtype: float64

In [34]:
#5 c
df.std(numeric_only=True)

student_id    14.577380
attendance    12.907663
marks         12.929130
age            1.850065
semester       1.688013
dtype: float64

In [35]:
#5 d
df.describe()

       student_id  attendance      marks        age   semester
count    50.00000   50.000000  50.000000  50.000000  50.000000
mean     25.50000   80.380000  57.041667  21.714286   3.260000
std      14.57738   12.907663  12.929130   1.850065   1.688013
min       1.00000   60.000000  34.000000  18.000000   1.000000
25%      13.25000   69.250000  57.041667  21.178571   2.000000
50%      25.50000   80.000000  57.041667  21.714286   3.000000
75%      37.75000   93.000000  57.041667  22.000000   4.750000
max      50.00000  100.000000  92.000000  25.000000   6.000000

In [37]:
#6 a
avg_marks=df['marks'].mean()
avg_marks

np.float64(57.04166666666667)

In [38]:
#6 b
above_avg = df[df['marks'] > avg_marks]
print(above_avg)

    student_id    name  gender        department  attendance  marks  \
3            4  Sachin    Male  Computer Science          85   90.0
7            8   Akash  Female        Electrical          63   60.0
10          11   Rohit  Female             Civil          62   77.0
11          12    Sona  Female  Computer Science          85   60.0
12          13   Rohit    Male             Civil          72   59.0
27          28   Rahul    Male        Mechanical          69   77.0
31          32  Nikhil  Female        Electrical          89   76.0
34          35   Meera  Female        Mechanical          66   92.0
37          38   Akash  Female        Mechanical          74   74.0
42          43   Pooja    Male        Mechanical          94   61.0
45          46   Vimal  Female        Mechanical          85   77.0
48          49   Vimal  Female        Mechanical          80   74.0

          age  semester        city scholarship
3   23.000000         5       Kochi          No
7   21.714286         6  Trivandrum         Yes
10  19.000000         1     Calicut         Yes
11  21.000000         3  Trivandrum         Yes
12  19.000000         3    Thrissur         Yes
27  21.714286         3    Thrissur         Yes
31  21.714286         6     Calicut          No
34  19.000000         5       Kochi          No
37  22.000000         2    Thrissur          No
42  21.714286         5       Kochi          No
45  21.714286         2       Kochi         Yes
48  25.000000         4  Trivandrum         Yes

In [42]:
#6 c
result = df[(df['attendance'] < 75) & (df['marks'] > avg_marks)]
result

,student_id,name,gender,department,attendance,marks,age,semester,city,scholarship
7,8,Akash,Female,Electrical,63,60.0,21.714286,6,Trivandrum,Yes
10,11,Rohit,Female,Civil,62,77.0,19.000000,1,Calicut,Yes
12,13,Rohit,Male,Civil,72,59.0,19.000000,3,Thrissur,Yes
27,28,Rahul,Male,Mechanical,69,77.0,21.714286,3,Thrissur,Yes
34,35,Meera,Female,Mechanical,66,92.0,19.000000,5,Kochi,No
37,38,Akash,Female,Mechanical,74,74.0,22.000000,2,Thrissur,No

In [41]:
#Q 7 a
df.groupby('department').size()

department
Civil               16
Computer Science    11
Electrical           8
Mechanical          15
dtype: int64

In [45]:
#q 7 b
dept_avg = df.groupby('department')['marks'].mean()
dept_avg

department
Civil               52.583333
Computer Science    56.753788
Electrical          56.901042
Mechanical          62.083333
Name: marks, dtype: float64

In [46]:
#q 7 c
highest_dept = dept_avg.idxmax()
highest_dept

'Mechanical'

In [48]:
#q 8
sorted_df = df.sort_values(by=['marks','attendance'],
                           ascending=[False,False])
sorted_df

,student_id,name,gender,department,attendance,marks,age,semester,city,scholarship
34,35,Meera,Female,Mechanical,66,92.000000,19.000000,5,Kochi,No
3,4,Sachin,Male,Computer Science,85,90.000000,23.000000,5,Kochi,No
45,46,Vimal,Female,Mechanical,85,77.000000,21.714286,2,Kochi,Yes
27,28,Rahul,Male,Mechanical,69,77.000000,21.714286,3,Thrissur,Yes
10,11,Rohit,Female,Civil,62,77.000000,19.000000,1,Calicut,Yes
31,32,Nikhil,Female,Electrical,89,76.000000,21.714286,6,Calicut,No
48,49,Vimal,Female,Mechanical,80,74.000000,25.000000,4,Trivandrum,Yes
37,38,Akash,Female,Mechanical,74,74.000000,22.000000,2,Thrissur,No
42,43,Pooja,Male,Mechanical,94,61.000000,21.714286,5,Kochi,No
11,12,Sona,Female,Computer Science,85,60.000000,21.000000,3,Trivandrum,Yes
7,8,Akash,Female,Electrical,63,60.000000,21.714286,6,Trivandrum,Yes
12,13,Rohit,Male,Civil,72,59.000000,19.000000,3,Thrissur,Yes
29,30,Nikhil,Female,Electrical,100,57.041667,21.714286,4,Trivandrum,No
4,5,Vimal,Female,Civil,99,57.041667,21.714286,1,Trivandrum,Yes
28,29,Kiran,Female,Mechanical,98,57.041667,21.714286,2,Calicut,No
33,34,Arjun,Female,Mechanical,98,57.041667,24.000000,1,Kochi,Yes
20,21,Asha,Male,Computer Science,96,57.041667,21.714286,2,Calicut,No
44,45,Rohit,Male,Electrical,96,57.041667,21.714286,6,Calicut,Yes
0,1,Rahul,Male,Mechanical,95,57.041667,21.714286,5,Thrissur,No
16,17,Nikhil,Male,Mechanical,95,57.041667,21.714286,4,Thrissur,No
19,20,Asha,Female,Electrical,95,57.041667,21.714286,3,Trivandrum,No
22,23,Rohit,Female,Civil,95,57.041667,23.000000,2,Kochi,Yes
23,24,Sona,Female,Civil,92,57.041667,18.000000,4,Calicut,No
35,36,Akash,Male,Computer Science,83,57.041667,25.000000,1,Calicut,Yes
8,9,Sachin,Male,Civil,80,57.041667,25.000000,3,Calicut,Yes
40,41,Sachin,Male,Computer Science,80,57.041667,21.714286,4,Calicut,Yes
6,7,Rahul,Male,Computer Science,78,57.041667,21.000000,6,Trivandrum,No
14,15,Arjun,Female,Civil,78,57.041667,25.000000,4,Trivandrum,No
30,31,Pooja,Female,Electrical,76,57.041667,23.000000,2,Kochi,Yes
13,14,Diya,Female,Computer Science,74,57.041667,21.714286,3,Calicut,Yes
17,18,Vimal,Male,Civil,73,57.041667,21.714286,2,Calicut,No
26,27,Amit,Female,Mechanical,73,57.041667,19.000000,4,Trivandrum,No
5,6,Anu,Female,Mechanical,66,57.041667,21.000000,3,Kochi,No
1,2,Anu,Male,Civil,62,57.041667,18.000000,1,Calicut,No
15,16,Amit,Male,Computer Science,62,57.041667,20.000000,1,Trivandrum,No
49,50,Pooja,Male,Electrical,62,57.041667,21.714286,4,Trivandrum,Yes
25,26,Vishnu,Female,Computer Science,60,57.041667,21.714286,1,Calicut,Yes
46,47,Neha,Male,Civil,60,57.041667,25.000000,1,Calicut,Yes
24,25,Riya,Male,Civil,70,56.000000,21.714286,1,Calicut,No
41,42,Kiran,Male,Mechanical,86,51.000000,24.000000,5,Kochi,Yes
38,39,Kavya,Male,Civil,93,50.000000,18.000000,5,Kochi,Yes
21,22,Rohit,Male,Mechanical,66,45.000000,20.000000,6,Trivandrum,No
18,19,Anu,Female,Computer Science,88,39.000000,22.000000,3,Trivandrum,Yes
32,33,Rohit,Female,Mechanical,93,38.000000,21.714286,5,Kochi,Yes
39,40,Pooja,Female,Civil,80,38.000000,21.714286,4,Trivandrum,No
2,3,Vishnu,Male,Computer Science,90,36.000000,21.714286,1,Calicut,Yes
47,48,Arjun,Male,Civil,73,36.000000,25.000000,6,Thrissur,No
9,10,Akash,Female,Civil,62,35.000000,22.000000,3,Kochi,No
36,37,Rohit,Female,Civil,99,34.000000,23.000000,1,Kochi,No
43,44,Pooja,Male,Electrical,69,34.000000,19.000000,4,Trivandrum,Yes

In [51]:
#q 9 a
df['result'] = df['marks'].apply(
    lambda x: 'Pass' if x >= 40 else 'Fail'
)

df[['marks','result']]

        marks result
0   57.041667   Pass
1   57.041667   Pass
2   36.000000   Fail
3   90.000000   Pass
4   57.041667   Pass
5   57.041667   Pass
6   57.041667   Pass
7   60.000000   Pass
8   57.041667   Pass
9   35.000000   Fail
10  77.000000   Pass
11  60.000000   Pass
12  59.000000   Pass
13  57.041667   Pass
14  57.041667   Pass
15  57.041667   Pass
16  57.041667   Pass
17  57.041667   Pass
18  39.000000   Fail
19  57.041667   Pass
20  57.041667   Pass
21  45.000000   Pass
22  57.041667   Pass
23  57.041667   Pass
24  56.000000   Pass
25  57.041667   Pass
26  57.041667   Pass
27  77.000000   Pass
28  57.041667   Pass
29  57.041667   Pass
30  57.041667   Pass
31  76.000000   Pass
32  38.000000   Fail
33  57.041667   Pass
34  92.000000   Pass
35  57.041667   Pass
36  34.000000   Fail
37  74.000000   Pass
38  50.000000   Pass
39  38.000000   Fail
40  57.041667   Pass
41  51.000000   Pass
42  61.000000   Pass
43  34.000000   Fail
44  57.041667   Pass
45  77.000000   Pass
46  57.041667   Pass
47  36.000000   Fail
48  74.000000   Pass
49  57.041667   Pass

In [52]:
#q 9 b
def performance(mark):
    if mark >= 80:
        return "Excellent"
    elif mark >= 50:
        return "Good"
    else:
        return "Needs Improvement"

df['performance'] = df['marks'].apply(performance)

(df[['marks','performance']])

        marks        performance
0   57.041667               Good
1   57.041667               Good
2   36.000000  Needs Improvement
3   90.000000          Excellent
4   57.041667               Good
5   57.041667               Good
6   57.041667               Good
7   60.000000               Good
8   57.041667               Good
9   35.000000  Needs Improvement
10  77.000000               Good
11  60.000000               Good
12  59.000000               Good
13  57.041667               Good
14  57.041667               Good
15  57.041667               Good
16  57.041667               Good
17  57.041667               Good
18  39.000000  Needs Improvement
19  57.041667               Good
20  57.041667               Good
21  45.000000  Needs Improvement
22  57.041667               Good
23  57.041667               Good
24  56.000000               Good
25  57.041667               Good
26  57.041667               Good
27  77.000000               Good
28  57.041667               Good
29  57.041667               Good
30  57.041667               Good
31  76.000000               Good
32  38.000000  Needs Improvement
33  57.041667               Good
34  92.000000          Excellent
35  57.041667               Good
36  34.000000  Needs Improvement
37  74.000000               Good
38  50.000000               Good
39  38.000000  Needs Improvement
40  57.041667               Good
41  51.000000               Good
42  61.000000               Good
43  34.000000  Needs Improvement
44  57.041667               Good
45  77.000000               Good
46  57.041667               Good
47  36.000000  Needs Improvement
48  74.000000               Good
49  57.041667               Good

In [53]:
#q 9 c
df['performance'].value_counts()

performance
Good                 39
Needs Improvement     9
Excellent             2
Name: count, dtype: int64

In [54]:
#q 10
df.reset_index(drop=True, inplace=True)
df.to_excel("cleaned_students_dataset.xlsx",
            index=False)

print("File exported successfully!")
from google.colab import files
files.download("cleaned_students_dataset.xlsx")

File exported successfully!